#!/bin/bash
set -euxo pipefail;
while [ ! -f /tmp/ports ]; do
  sleep 0.1;
done;
sleep 0.1;
source /tmp/ports;
export KAFKA_NODE_ID=1
export KAFKA_PROCESS_ROLES=broker,controller
export KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
export KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
export KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
export KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
export KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
export KAFKA_NUM_PARTITIONS=1
export KAFKA_LISTENERS=INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093;
export KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:$PORT_9092;
export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT;
export KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER;
export KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL;
exec /etc/kafka/docker/run
