#!/bin/bash
set -euxo pipefail;
while [ ! -f /tmp/ports ]; do
  sleep 0.1;
done;
sleep 0.1;
source /tmp/ports;
export KAFKA_LISTENERS=INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093;
export KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:$PORT_9092;
export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT;
export KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER;
export KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL;
exec /docker-entrypoint.sh start
